################################################################################
# Title: Cantleykinase_analysis.R
#
# Author: Mirjam van Bentum
# Date: 14.03.2015
#
# Purpose:
#   1) Read in the moderated t-test (limma) results (stored in "KinLibIn.csv")
#      which have been pre-formatted for the S/T kinase motif enrichment tool:
#      https://kinase-library.phosphosite.org/
#   2) Split the combined input ("KinLibIn.csv") back into 18 per-comparison
#      .txt files, each corresponding to a single (group × cell line) condition.
#      This recreates the original file structure that can be directly submitted
#      to the kinase library tool if desired.
#   3) Read the merged output from the kinase tool ("KinLibOut.csv"), containing
#      the kinase motif analysis results for all (group × cell line) comparisons. 
#      (This can also be performed with outputs as generated by the tool)
#   4) Generate volcano plots (log2 fold change vs. -log10 p-value) across
#      conditions, save individual PDFs, and combine them into one multi-panel
#      figure.
#
# Thresholds tool
#   - log2 fold change cutoff: > 0.1
#   - p-value cutoff: < 0.05
#
# Dependencies:
#   - R packages: tidyverse, ggplot2, ggrepel, patchwork
#   - Files:
#       "KinLibIn.csv"  -> The merged input data (limma output) in long format
#       "KinLibOut.csv" -> The concatenated output from the S/T kinase tool
#   Provided in Supplementary Data of associated Manuscript
#
# Output (created in ../output/):
#   - 18 split input files: one .txt per (group × cell line) for the kinase tool
#   - Volcano plots: individual PDFs and one combined PDF
#   - A CSV ("AllVolcanoPlotData.csv") capturing the data behind each plot
#
# Reproducibility:
#   - Place "KinLibIn.csv" and "KinLibOut.csv" in the "data" directory
#   - Run this script from the "script" directory
#   - All output is written to the "output" directory
#
################################################################################

##############################################
# 1) PACKAGES AND SETUP
##############################################

library(tidyverse)
library(ggrepel)
library(patchwork)

# Create an output directory if needed
if (!dir.exists("../output")) {
  dir.create("../output")
}

# Mapping from oldname → newname
plottitle_df <- tibble(
  oldname = c("SynSign","SynSign2","LMvsBSAinDMSO",
              "LMvsBSAinMEKi","MEKivsDMSOinBSA","MEKivsDMSOinLM"),
  newname = c("Interaction","Interaction2","GFmix w/o MEKi",
              "GFmix w MEKi","MEKi w/o GFmix","MEKi w GFmix")
)

# All 6 groups (including SynSign2) if needed
groups_all <- c("SynSign","SynSign2","LMvsBSAinDMSO",
                "LMvsBSAinMEKi","MEKivsDMSOinBSA","MEKivsDMSOinLM")

# 3 cell lines
CellLines <- c("HCT116", "Caco2", "DLD1")


##############################################
# 2) READ KINLIBIN AND SPLIT INTO 18 FILES
##############################################

# 'KinLibIn.csv' is the pivoted moderated t-test output
# in one single file (long format).
# For reproducibility purposes this code reads this file
# and then split it back to 18 files that the
# kinase tool expects.

kin_in_path <- "../data/KinLibIn.csv"  # Adjust path if needed
all_dataIn <- read_csv(kin_in_path, show_col_types = FALSE)

# We'll create a folder for these 18 input files
input_split_dir <- "../output/KinLibIn_Split"
if (!dir.exists(input_split_dir)) {
  dir.create(input_split_dir)
}

# For each old comparison name and cell line in all_dataIn, write a separate file
for (ii in groups_all) {
  for (CL in CellLines) {
    # Subset the data
    df_sub <- all_dataIn %>%
      filter(
        old_comparison == ii,
        cell_line == CL
      )
    
    # Skip if no rows
    if (nrow(df_sub) == 0) next
    
    # Re-pivot to wide: we want columns like FC.<comparison> and pval.<comparison>
    # so that each file is in the original format the kinase tool uses
    # We'll do an example that tries to produce something like:
    #   <some sequence columns>, FC.<ii>, pval.<ii>, ...
    # Adjust if your original wide format had more columns
    df_wide <- df_sub %>%
      select(-comparison, -newname, -date) %>%  # remove extra columns if not needed
      pivot_wider(
        names_from  = old_comparison,   # or "ii" if you prefer
        values_from = c(FC, pval),      # from the 2 columns in the long format
        names_glue  = "{.value}.{old_comparison}"
      )
    
    # Construct a filename for the old comparison + cell line
    # e.g. 2024-02-15_HCT116_FC.SynSign_pval.SynSign.txt
    # You can adapt this naming scheme to match the tool's needs:
    out_filename <- file.path(
      input_split_dir,
      paste0("Input_", CL, "_", ii, ".txt")
    )
    
    # Write the subset to disk
    write_tsv(df_wide, out_filename)
  }
}

#These 18 files can be used as input for the Cantley-lab tool

##############################################
# 3) READ KINLIBOUT AND GENERATE PLOTS
##############################################

# 'KinLibOut.csv' is the single-file aggregated output
# from the kinase library tool.
kin_out_path <- "../data/KinLibOut.csv"  # Adjust path if needed
all_dat <- read_csv(kin_out_path, show_col_types = FALSE)

# The tool presumably merges columns like: "dominant_enrichment_value_log2", 
# "dominant_p_value_log10_abs", etc. We'll verify those columns exist:
# glimpse(all_dat)

hold_plots <- list()
plot_count <- 1

# We'll store the plotting data in 'allSourceData'
allSourceData <- tibble()

# We'll limit ourselves to 5 groups if we are excluding SynSign2
groups_for_plots <- c("SynSign","LMvsBSAinDMSO","LMvsBSAinMEKi",
                      "MEKivsDMSOinBSA","MEKivsDMSOinLM")

for (ii in groups_for_plots) {
  # Get the friendly name from plottitle_df
  new_name <- plottitle_df %>%
    filter(oldname == ii) %>%
    pull(newname)
  
  for (CL in CellLines) {
    # Subset the aggregated data for this group + cell line
    dat <- all_dat %>%
      filter(Group == new_name, CellLine == CL)
    
    if (nrow(dat) == 0) {
      message("No data for group=", ii, " (", new_name, ") / cell_line=", CL)
      next
    }
    
    # Annotate significance
    plot_dat <- dat %>%
      mutate(
        sign.Hits = case_when(
          dominant_p_value <= 0.05 & dominant_enrichment_value_log2 > 0 ~ "upregulated",
          dominant_p_value <= 0.05 & dominant_enrichment_value_log2 < 0 ~ "downregulated",
          TRUE                                                         ~ "insignificant"
        ),
        sign.Hits = factor(sign.Hits, levels = c("upregulated","downregulated","insignificant"))
      )
    
    # Keep some columns in allSourceData
    tmp_data <- plot_dat %>%
      select(
        kinase, kinase_group,
        dominant_enrichment_value_log2, dominant_p_value_log10_abs
      ) %>%
      mutate(
        sign.Hits   = plot_dat$sign.Hits,
        group       = new_name,
        cell_line   = CL
      )
    allSourceData <- bind_rows(allSourceData, tmp_data)
    
    # Volcano plot
    p <- ggplot(
      plot_dat,
      aes(
        x = dominant_enrichment_value_log2,
        y = dominant_p_value_log10_abs,
        color = sign.Hits
      )
    ) +
      geom_point(alpha = 0.5) +
      theme_bw() +
      geom_hline(yintercept = abs(log10(0.05)), color = "red3", lty = 2) +
      geom_text_repel(
        data = filter(plot_dat, sign.Hits != "insignificant"),
        aes(label = kinase),
        size = 3, min.segment.length = 0.1, max.overlaps = 10
      ) +
      ylab("-log10(pval)") +
      xlab("log2(EV)") +
      scale_color_manual(values = list(
        "insignificant" = "grey50",
        "downregulated" = "blue3",
        "upregulated"   = "red3"
      )) +
      ggtitle(paste(CL, new_name)) +
      theme(
        text = element_text(size = 9),
        legend.position = "none",
        title = element_text(size = 11)
      )
    
    hold_plots[[plot_count]] <- p
    plot_count <- plot_count + 1
    
    # (Optional) Save the individual plot
    outfile_individual <- file.path(
      "../output",
      paste0("Volcano_", CL, "_", ii, ".pdf")
    )
    ggsave(outfile_individual, p, width = 4, height = 4)
  }
}

# Combine all plots
combined_plot <- reduce(hold_plots, `+`) + plot_layout(ncol = 3)

# Save the combined plot
ggsave(
  "../output/Volcano_Combined.pdf",
  plot   = combined_plot,
  width  = 12,
  height = 17
)

# Write the final source data for these plots
write_csv(
  allSourceData,
  "../output/AllVolcanoPlotData.csv"
)

message("Done! Check the '../output' folder for your files.")
